#!/usr/bin/env python3
from string import ascii_letters, digits, punctuation
import random


def generate(length=12):
    result = []

    for i in range(length):
        possible = ascii_letters + digits + punctuation
        result.append(random.choice(possible))

    return "".join(result)

print(generate())
