#!/usr/bin/env python3
from string import ascii_letters, digits, punctuation
import random

# TODO use argparse to take -n length as argument, -s - save to specified file,
# -a add to ~/.passwords directory
# TODO add tests to test arguments
# TODO add readme
# TODO set up as python package for pypi

def generate(length=12):
    result = []

    for i in range(length):
        possible = ascii_letters + digits + punctuation
        result.append(random.choice(possible))

    return "".join(result)

print(generate())
